var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/contact/route.js")
R.c("server/chunks/[externals]__0o9dz8e._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/_0veaa4n._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_next-internal_server_app_api_contact_route_actions_02158u4.js")
R.m(86590)
module.exports=R.m(86590).exports
