var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/login/route.js")
R.c("server/chunks/[root-of-the-server]__05_0jhc._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/[root-of-the-server]__0aivsv~._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_login_route_actions_0zukc38.js")
R.m(30450)
module.exports=R.m(30450).exports
