var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/forgot-password/route.js")
R.c("server/chunks/[root-of-the-server]__0._fq_v._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/[root-of-the-server]__0aivsv~._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_forgot-password_route_actions_0txet3j.js")
R.m(69157)
module.exports=R.m(69157).exports
