var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/uploads/route.js")
R.c("server/chunks/[root-of-the-server]__09up88k._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_uploads_route_actions_0u3fsc3.js")
R.m(58702)
module.exports=R.m(58702).exports
