var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/wishlist/toggle/route.js")
R.c("server/chunks/[root-of-the-server]__057v8ih._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/src_lib_09v_oux._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_next-internal_server_app_api_wishlist_toggle_route_actions_12wbyc~.js")
R.m(54827)
module.exports=R.m(54827).exports
