var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/register/route.js")
R.c("server/chunks/[root-of-the-server]__0xhhl8w._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/[root-of-the-server]__0aivsv~._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_register_route_actions_096_y_i.js")
R.m(6706)
module.exports=R.m(6706).exports
