var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/verify-email/route.js")
R.c("server/chunks/[root-of-the-server]__0gs4k3c._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/[root-of-the-server]__0aivsv~._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_verify-email_route_actions_0y0eghp.js")
R.m(84311)
module.exports=R.m(84311).exports
