var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/wishlist/route.js")
R.c("server/chunks/[root-of-the-server]__0z~tp.4._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/src_lib_09v_oux._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_next-internal_server_app_api_wishlist_route_actions_0l--8p2.js")
R.m(40192)
module.exports=R.m(40192).exports
