var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/instructions/route.js")
R.c("server/chunks/[root-of-the-server]__01ojwu0._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/[root-of-the-server]__03ifl~6._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_instructions_route_actions_0clds8f.js")
R.m(47211)
module.exports=R.m(47211).exports
