var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/me/courses/route.js")
R.c("server/chunks/[root-of-the-server]__0a3ajjd._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/[root-of-the-server]__05-3j82._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/src_lib_08erbgk._.js")
R.c("server/chunks/_next-internal_server_app_api_me_courses_route_actions_0tothkc.js")
R.m(67312)
module.exports=R.m(67312).exports
