var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/me/profile/route.js")
R.c("server/chunks/[root-of-the-server]__0snld5i._.js")
R.c("server/chunks/[root-of-the-server]__05-3j82._.js")
R.c("server/chunks/_08mgfak._.js")
R.c("server/chunks/_0er093h._.js")
R.c("server/chunks/src_lib_validators_schemas_ts_0s7u-no._.js")
R.c("server/chunks/_00msskd._.js")
R.c("server/chunks/src_lib_08erbgk._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_next-internal_server_app_api_me_profile_route_actions_00t7bi1.js")
R.m(12798)
module.exports=R.m(12798).exports
